from __future__ import annotations

import os
import shlex
import subprocess
import time
import uuid
from typing import Any

from .capture import codex_for_pane
from .desktop import place_by_title, remap_monitor, remap_workspace
from .util import CommandError, run


def _tmux_exists(name: str) -> bool:
    return subprocess.run(["tmux", "has-session", "-t", f"={name}:"], capture_output=True).returncode == 0


def _pane_command(pane: dict[str, Any]) -> list[str]:
    codex = pane.get("codex") or {}
    session_id = codex.get("session_id")
    if session_id:
        return ["codex", "resume", session_id]
    return [os.environ.get("SHELL", "/bin/sh")]


def _shell_join(command: list[str]) -> str:
    return " ".join(shlex.quote(value) for value in command)


def _pane_shell_command(pane: dict[str, Any]) -> str:
    command = _pane_command(pane)
    shell = os.environ.get("SHELL", "/bin/sh")
    if (pane.get("codex") or {}).get("session_id"):
        # A failed or later-closed Codex process must not remove the pane and
        # cascade into lost windows or a lost tmux session.
        return f"{_shell_join(command)}; exec {_shell_join([shell])}"
    return f"exec {_shell_join(command)}"


def _tmux_state(name: str) -> dict[int, dict[str, Any]]:
    fields = "\t".join([
        "#{window_index}", "#{window_name}", "#{window_id}",
        "#{pane_index}", "#{pane_id}", "#{pane_pid}", "#{pane_current_path}",
    ])
    try:
        output = run(["tmux", "list-panes", "-s", "-t", f"={name}:", "-F", fields])
    except CommandError:
        return {}
    windows: dict[int, dict[str, Any]] = {}
    for line in output.splitlines():
        parts = line.split("\t", 6)
        if len(parts) != 7:
            continue
        win_idx, win_name, win_id, pane_idx, pane_id, pane_pid, cwd = parts
        window = windows.setdefault(int(win_idx), {
            "name": win_name, "id": win_id, "panes": {},
        })
        window["panes"][int(pane_idx)] = {
            "id": pane_id, "pid": int(pane_pid), "cwd": cwd,
        }
    return windows


def _codex_ids(session: dict[str, Any]) -> set[str]:
    return {
        pane["codex"]["session_id"]
        for window in session.get("windows", []) for pane in window.get("panes", [])
        if pane.get("codex") and pane["codex"].get("session_id")
    }


def _live_codex_ids(state: dict[int, dict[str, Any]]) -> set[str]:
    result = set()
    for window in state.values():
        for pane in window["panes"].values():
            codex = codex_for_pane(pane["pid"], pane["cwd"])
            if codex and codex.get("session_id"):
                result.add(codex["session_id"])
    return result


def _same_tmux_session(session: dict[str, Any], state: dict[int, dict[str, Any]]) -> bool:
    saved_windows = {int(window["index"]): window for window in session.get("windows", [])}
    overlap = set(saved_windows).intersection(state)
    if not overlap:
        return False
    if any(saved_windows[index]["name"] != state[index]["name"] for index in overlap):
        return False
    saved_ids = _codex_ids(session)
    live_ids = _live_codex_ids(state)
    if saved_ids:
        # Never repair a same-named session unless its live Codex identities
        # prove that it belongs to this recipe. This avoids mutating an
        # unrelated numeric/default-named session.
        return bool(live_ids) and live_ids.issubset(saved_ids)
    return True


def _available_tmux_name(name: str) -> str:
    base = f"{name}-wsctl"
    candidate = base
    suffix = 2
    while _tmux_exists(candidate):
        candidate = f"{base}-{suffix}"
        suffix += 1
    return candidate


def _split_saved_pane(
    target: str,
    pane: dict[str, Any],
    *,
    dry_run: bool,
    placeholder: str,
) -> str:
    if dry_run:
        return placeholder
    return run([
        "tmux", "split-window", "-d", "-t", target, "-c", pane["cwd"],
        "-P", "-F", "#{pane_id}", _pane_shell_command(pane),
    ]).strip()


def _finish_window(
    target: str,
    window: dict[str, Any],
    pane_targets: dict[int, str],
    *,
    dry_run: bool,
) -> None:
    if dry_run:
        return
    if len(window.get("panes", [])) > 1 and window.get("layout"):
        # Layout strings are generated by tmux itself; tmux validates them.
        run(["tmux", "select-layout", "-t", target, window["layout"]], check=False)
    active = next((pane for pane in window.get("panes", []) if pane.get("active")), None)
    if active and int(active["index"]) in pane_targets:
        run(["tmux", "select-pane", "-t", pane_targets[int(active["index"])]])


def _create_window(
    name: str,
    window: dict[str, Any],
    *,
    dry_run: bool,
) -> str:
    first_pane = window["panes"][0]
    command = [
        "tmux", "new-window", "-d", "-t", f"={name}:{int(window['index'])}",
        "-n", window["name"], "-c", first_pane["cwd"],
        "-P", "-F", "#{window_id}", _pane_shell_command(first_pane),
    ]
    target = f"={name}:<window-{window['index']}>" if dry_run else run(command).strip()
    pane_targets = {
        int(first_pane["index"]): (
            f"{target}.<pane-{first_pane['index']}>"
            if dry_run else run(["tmux", "display-message", "-p", "-t", target, "#{pane_id}"]).strip()
        )
    }
    for pane in window["panes"][1:]:
        pane_targets[int(pane["index"])] = _split_saved_pane(
            target, pane, dry_run=dry_run,
            placeholder=f"{target}.<pane-{pane['index']}>",
        )
    _finish_window(target, window, pane_targets, dry_run=dry_run)
    if not dry_run:
        run(["tmux", "rename-window", "-t", target, window["name"]])
    return target


def _reconcile_tmux(
    name: str,
    session: dict[str, Any],
    state: dict[int, dict[str, Any]],
    *,
    dry_run: bool,
) -> list[str]:
    actions = [f"reuse tmux session {name}"]
    active_target = None
    for window in session.get("windows", []):
        index = int(window["index"])
        current = state.get(index)
        if current is None:
            target = _create_window(name, window, dry_run=dry_run)
            actions.append(f"restore missing tmux window {name}:{index} ({window['name']})")
        else:
            target = current["id"]
            pane_targets = {
                int(pane_index): pane["id"]
                for pane_index, pane in current["panes"].items()
            }
            for pane in window.get("panes", []):
                pane_index = int(pane["index"])
                if pane_index in pane_targets:
                    continue
                pane_targets[pane_index] = _split_saved_pane(
                    target, pane, dry_run=dry_run,
                    placeholder=f"{target}.<pane-{pane_index}>",
                )
                actions.append(f"restore missing tmux pane {name}:{index}.{pane_index}")
            if len(pane_targets) == len(window.get("panes", [])):
                _finish_window(target, window, pane_targets, dry_run=dry_run)
        if window.get("active"):
            active_target = target
    if active_target and not dry_run:
        run(["tmux", "select-window", "-t", active_target])
    return actions


def recreate_tmux(session: dict[str, Any], *, dry_run: bool = False) -> tuple[str, list[str]]:
    saved_name = session["name"]
    windows = session.get("windows", [])
    if not windows:
        return saved_name, [f"skip empty tmux session {saved_name}"]

    name = saved_name
    actions: list[str] = []
    if _tmux_exists(name):
        state = _tmux_state(name)
        if _same_tmux_session(session, state):
            return name, _reconcile_tmux(name, session, state, dry_run=dry_run)
        name = _available_tmux_name(saved_name)
        actions.append(f"tmux name {saved_name} is in use; restore as {name}")

    first_window = windows[0]
    first_pane = first_window["panes"][0]
    command = [
        "tmux", "new-session", "-d", "-s", name,
        "-n", first_window["name"], "-c", first_pane["cwd"],
        _pane_shell_command(first_pane),
    ]
    actions.append("create " + name)
    if not dry_run:
        run(command)
        target = run(["tmux", "display-message", "-p", "-t", f"={name}:", "#{window_id}"]).strip()
        actual_index = int(run([
            "tmux", "display-message", "-p", "-t", target, "#{window_index}",
        ]).strip())
        saved_index = int(first_window["index"])
        if actual_index != saved_index:
            run(["tmux", "move-window", "-s", target, "-t", f"={name}:{saved_index}"])
    else:
        target = f"={name}:<first-window>"

    pane_targets = {
        int(first_pane["index"]): (
            f"{target}.<pane-{first_pane['index']}>"
            if dry_run else run(["tmux", "display-message", "-p", "-t", target, "#{pane_id}"]).strip()
        )
    }
    for pane in first_window["panes"][1:]:
        pane_targets[int(pane["index"])] = _split_saved_pane(
            target, pane, dry_run=dry_run,
            placeholder=f"{target}.<pane-{pane['index']}>",
        )
    _finish_window(target, first_window, pane_targets, dry_run=dry_run)
    active_target = target if first_window.get("active") else None

    for window in windows[1:]:
        target = _create_window(name, window, dry_run=dry_run)
        if window.get("active"):
            active_target = target
    if active_target and not dry_run:
        run(["tmux", "select-window", "-t", active_target])
    return name, actions


def launch_terminal(session: dict[str, Any], *, place: bool = True, dry_run: bool = False) -> str:
    name = session["name"]
    title = f"wsctl:{name}:{uuid.uuid4().hex[:8]}"
    command = [
        "alacritty", "--title", title, "-o", "window.dynamic_title=false",
        "-e", "tmux", "attach-session", "-t", f"={name}:",
    ]
    if dry_run:
        return "launch " + " ".join(shlex.quote(item) for item in command)
    subprocess.Popen(command, start_new_session=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    placement = session.get("placement")
    if place and placement:
        placement = remap_monitor(remap_workspace(placement))
        for _ in range(30):
            if place_by_title(title, placement):
                return f"launched {name}"
            time.sleep(0.1)
        return f"launched {name} (window placement failed)"
    return f"launched {name}"
